done: facing error
ImportError: cannot import name 'DiaryMenu' from partially initialized module 'src.main_application.diary_menu' (most likely due to a circular import)